<?php

namespace Proxies\__CG__\GarageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employe extends \GarageBundle\Entity\Employe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'cinemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'nomemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'prenomemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'statutsoc', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'adresseemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'datenaissemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'telemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'typeemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'salaire', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'statutemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'id', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'Fiches'];
        }

        return ['__isInitialized__', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'cinemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'nomemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'prenomemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'statutsoc', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'adresseemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'datenaissemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'telemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'typeemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'salaire', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'statutemp', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'id', '' . "\0" . 'GarageBundle\\Entity\\Employe' . "\0" . 'Fiches'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCinemp($cinemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinemp', [$cinemp]);

        return parent::setCinemp($cinemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinemp', []);

        return parent::getCinemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomemp($nomemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomemp', [$nomemp]);

        return parent::setNomemp($nomemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomemp', []);

        return parent::getNomemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomemp($prenomemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomemp', [$prenomemp]);

        return parent::setPrenomemp($prenomemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomemp', []);

        return parent::getPrenomemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutsoc($statutsoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutsoc', [$statutsoc]);

        return parent::setStatutsoc($statutsoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutsoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutsoc', []);

        return parent::getStatutsoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseemp($adresseemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseemp', [$adresseemp]);

        return parent::setAdresseemp($adresseemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseemp', []);

        return parent::getAdresseemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaissemp($datenaissemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaissemp', [$datenaissemp]);

        return parent::setDatenaissemp($datenaissemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaissemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaissemp', []);

        return parent::getDatenaissemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelemp($telemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelemp', [$telemp]);

        return parent::setTelemp($telemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelemp', []);

        return parent::getTelemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeemp($typeemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeemp', [$typeemp]);

        return parent::setTypeemp($typeemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeemp', []);

        return parent::getTypeemp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalaire($salaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalaire', [$salaire]);

        return parent::setSalaire($salaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaire', []);

        return parent::getSalaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutemp($statutemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutemp', [$statutemp]);

        return parent::setStatutemp($statutemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutemp', []);

        return parent::getStatutemp();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function _construct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_construct', []);

        return parent::_construct();
    }

}
