<?php

namespace Proxies\__CG__\GarageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Compte extends \GarageBundle\Entity\Compte implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'nomprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'prenomprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'telprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'adresseprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'mailprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'modelevoit', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'marquevoit', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'immatvoit', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'cinprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'id', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'Fiches'];
        }

        return ['__isInitialized__', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'nomprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'prenomprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'telprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'adresseprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'mailprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'modelevoit', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'marquevoit', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'immatvoit', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'cinprop', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'id', '' . "\0" . 'GarageBundle\\Entity\\Compte' . "\0" . 'Fiches'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Compte $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFiches($Fiches)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiches', [$Fiches]);

        return parent::setFiches($Fiches);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiches()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiches', []);

        return parent::getFiches();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomprop($nomprop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomprop', [$nomprop]);

        return parent::setNomprop($nomprop);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomprop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomprop', []);

        return parent::getNomprop();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomprop($prenomprop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomprop', [$prenomprop]);

        return parent::setPrenomprop($prenomprop);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomprop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomprop', []);

        return parent::getPrenomprop();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelprop($telprop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelprop', [$telprop]);

        return parent::setTelprop($telprop);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelprop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelprop', []);

        return parent::getTelprop();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseprop($adresseprop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseprop', [$adresseprop]);

        return parent::setAdresseprop($adresseprop);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseprop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseprop', []);

        return parent::getAdresseprop();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailprop($mailprop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailprop', [$mailprop]);

        return parent::setMailprop($mailprop);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailprop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailprop', []);

        return parent::getMailprop();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelevoit($modelevoit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelevoit', [$modelevoit]);

        return parent::setModelevoit($modelevoit);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelevoit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelevoit', []);

        return parent::getModelevoit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarquevoit($marquevoit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarquevoit', [$marquevoit]);

        return parent::setMarquevoit($marquevoit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarquevoit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarquevoit', []);

        return parent::getMarquevoit();
    }

    /**
     * {@inheritDoc}
     */
    public function setImmatvoit($immatvoit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImmatvoit', [$immatvoit]);

        return parent::setImmatvoit($immatvoit);
    }

    /**
     * {@inheritDoc}
     */
    public function getImmatvoit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImmatvoit', []);

        return parent::getImmatvoit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinprop($cinprop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinprop', [$cinprop]);

        return parent::setCinprop($cinprop);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinprop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinprop', []);

        return parent::getCinprop();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function _construct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_construct', []);

        return parent::_construct();
    }

}
