<?php

namespace Proxies\__CG__\GarageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Piece extends \GarageBundle\Entity\Piece implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'refpiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'marquepiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'prixpiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'typepiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'libellepiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'id'];
        }

        return ['__isInitialized__', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'refpiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'marquepiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'prixpiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'typepiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'libellepiece', '' . "\0" . 'GarageBundle\\Entity\\Piece' . "\0" . 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Piece $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setRefpiece($refpiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefpiece', [$refpiece]);

        return parent::setRefpiece($refpiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefpiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefpiece', []);

        return parent::getRefpiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarquepiece($marquepiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarquepiece', [$marquepiece]);

        return parent::setMarquepiece($marquepiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarquepiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarquepiece', []);

        return parent::getMarquepiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixpiece($prixpiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixpiece', [$prixpiece]);

        return parent::setPrixpiece($prixpiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixpiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixpiece', []);

        return parent::getPrixpiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypepiece($typepiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypepiece', [$typepiece]);

        return parent::setTypepiece($typepiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypepiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypepiece', []);

        return parent::getTypepiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibellepiece($libellepiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibellepiece', [$libellepiece]);

        return parent::setLibellepiece($libellepiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibellepiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibellepiece', []);

        return parent::getLibellepiece();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
